kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack_demo
        # Send severity=slack alerts to slack.
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m

    receivers:
    - name: devnull
    - name: eventmanagement
    webhook_configs:
    - send_resolved: false
        http_config:
        tls_config:
            insecure_skip_verify: true
        url: http://ime-ws-service/ime-ws/api/v1/internal/wallet
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
data:
  default.tmpl: |
